spring.application.name=nongki
server.port=8080

spring.datasource.url=jdbc:mysql://localhost:3306/nongki?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

security.jwt.secret-key=ZjI2NzRmYjY3YTQyZWQ5MTVjMDBjMWY4MjFlNGZkMzNlMjg1M2M0MTQwODE2YmE4ZjUxNDk1ZjA1M2RjZTUxNw==

security.jwt.expiration-time=3600000

rsa.private-key=classpath:certs/private.pem
rsa.public-key=classpath:certs/public.pem